# Generated by Django 4.2.3 on 2023-07-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experince',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
